import React, { useState, useMemo } from 'react';
import { Route, Layers, Copy, Check, Terminal, Table, ArrowRight, ShieldCheck } from 'lucide-react';

export interface OspfInterface {
  id: string;
  name: string;
  bandwidthMbps: number;
  area: number;
  ipNetwork: string;
}

export const OspfPlanner: React.FC = () => {
  const [refBandwidthMbps, setRefBandwidthMbps] = useState(10000); // 10 Gbps (10,000 Mbps)
  const [processId, setProcessId] = useState(1);
  const [routerId, setRouterId] = useState('1.1.1.1');
  const [interfaces, setInterfaces] = useState<OspfInterface[]>([
    { id: '1', name: 'GigabitEthernet0/0/0', bandwidthMbps: 1000, area: 0, ipNetwork: '10.0.0.0/30' },
    { id: '2', name: 'TenGigabitEthernet0/1/0', bandwidthMbps: 10000, area: 0, ipNetwork: '10.0.1.0/24' },
    { id: '3', name: 'FastEthernet0/0/1', bandwidthMbps: 100, area: 1, ipNetwork: '10.1.0.0/24' },
    { id: '4', name: 'Loopback0', bandwidthMbps: 10000, area: 0, ipNetwork: '1.1.1.1/32' }
  ]);
  const [copiedKey, setCopiedKey] = useState<string | null>(null);

  // OSPF Interface Cost = Ref Bandwidth / Interface Bandwidth (minimum 1)
  const evaluatedInterfaces = useMemo(() => {
    return interfaces.map((intf) => {
      const rawCost = refBandwidthMbps / intf.bandwidthMbps;
      const cost = Math.max(1, Math.round(rawCost));
      return {
        ...intf,
        calculatedCost: cost
      };
    });
  }, [interfaces, refBandwidthMbps]);

  // Cisco OSPF Config Generator
  const ciscoOspfConfig = `! Cisco IOS OSPF Configuration
router ospf ${processId}
 router-id ${routerId}
 auto-cost reference-bandwidth ${refBandwidthMbps}
 ! Interfaces & Areas
${evaluatedInterfaces.map(i => ` network ${i.ipNetwork.split('/')[0]} 0.0.0.255 area ${i.area}`).join('\n')}
!
! Explicit interface tuning:
${evaluatedInterfaces.map(i => `interface ${i.name}\n ip ospf cost ${i.calculatedCost}\n ip ospf priority 100`).join('\n!')}`;

  const copyToClipboard = (text: string, key: string) => {
    navigator.clipboard.writeText(text);
    setCopiedKey(key);
    setTimeout(() => setCopiedKey(null), 2000);
  };

  const lsaTypes = [
    { type: 'Type 1 (Router LSA)', flood: 'Within Area', desc: 'Generated by every router describing its local links and states.' },
    { type: 'Type 2 (Network LSA)', flood: 'Within Area', desc: 'Generated by Designated Router (DR) representing multi-access segment.' },
    { type: 'Type 3 (Summary LSA)', flood: 'Inter-Area', desc: 'Generated by Area Border Router (ABR) advertising subnets between areas.' },
    { type: 'Type 4 (ASBR Summary)', flood: 'Inter-Area', desc: 'Generated by ABR advertising route to reach AS External Boundary Router.' },
    { type: 'Type 5 (External LSA)', flood: 'Entire OSPF Domain', desc: 'Generated by ASBR containing redistributed external routes.' },
    { type: 'Type 7 (NSSA External)', flood: 'NSSA Only', desc: 'Used in Not-So-Stubby Areas, converted to Type 5 by ABR.' }
  ];

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl p-6 shadow-sm">
        <div className="flex items-center space-x-3 mb-6">
          <div className="p-2.5 rounded-lg bg-teal-50 dark:bg-teal-950/60 text-teal-600 dark:text-teal-400">
            <Route className="h-6 w-6" />
          </div>
          <div>
            <h1 className="text-xl font-bold text-slate-900 dark:text-white">OSPF Multi-Area Planner & Metric Cost Matrix</h1>
            <p className="text-xs sm:text-sm text-slate-500 dark:text-slate-400">
              Calculate SPF interface link costs with customizable reference bandwidths, LSA type matrix, and DR/BDR election priority.
            </p>
          </div>
        </div>

        {/* Global Settings */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
          <div>
            <label className="block text-xs font-semibold uppercase tracking-wider text-slate-600 dark:text-slate-400 mb-1">
              OSPF Process ID
            </label>
            <input
              type="number"
              value={processId}
              onChange={(e) => setProcessId(parseInt(e.target.value, 10) || 1)}
              className="w-full font-mono text-sm px-3.5 py-2 bg-slate-50 dark:bg-slate-950 border rounded-lg dark:text-white"
            />
          </div>

          <div>
            <label className="block text-xs font-semibold uppercase tracking-wider text-slate-600 dark:text-slate-400 mb-1">
              Router ID (32-bit dotted-decimal)
            </label>
            <input
              type="text"
              value={routerId}
              onChange={(e) => setRouterId(e.target.value)}
              className="w-full font-mono text-sm px-3.5 py-2 bg-slate-50 dark:bg-slate-950 border rounded-lg dark:text-white font-bold text-teal-600 dark:text-teal-400"
            />
          </div>

          <div>
            <label className="block text-xs font-semibold uppercase tracking-wider text-slate-600 dark:text-slate-400 mb-1">
              Reference Bandwidth
            </label>
            <select
              value={refBandwidthMbps}
              onChange={(e) => setRefBandwidthMbps(parseInt(e.target.value, 10))}
              className="w-full font-mono text-sm px-3.5 py-2 bg-slate-50 dark:bg-slate-950 border rounded-lg dark:text-white font-bold"
            >
              <option value={100}>100 Mbps (Default Cisco Legacy)</option>
              <option value={1000}>1,000 Mbps (1 Gbps)</option>
              <option value={10000}>10,000 Mbps (10 Gbps Recommended)</option>
              <option value={100000}>100,000 Mbps (100 Gbps Datacenter)</option>
            </select>
          </div>
        </div>
      </div>

      {/* Interface Cost Calculation Table */}
      <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl p-5 shadow-sm space-y-4">
        <h2 className="text-sm font-bold uppercase tracking-wider text-slate-900 dark:text-white flex items-center space-x-2">
          <Table className="h-4 w-4 text-teal-500" />
          <span>Interface Bandwidth to OSPF Metric Cost Evaluation</span>
        </h2>

        <div className="overflow-x-auto border border-slate-200 dark:border-slate-800 rounded-lg">
          <table className="w-full text-left text-xs font-mono">
            <thead className="bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300">
              <tr>
                <th className="p-2.5">Interface</th>
                <th className="p-2.5">Bandwidth (Mbps)</th>
                <th className="p-2.5">Area</th>
                <th className="p-2.5">Network Prefix</th>
                <th className="p-2.5 text-right font-bold text-teal-600 dark:text-teal-400">Computed Cost</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-200 dark:divide-slate-800">
              {evaluatedInterfaces.map((intf) => (
                <tr key={intf.id} className="hover:bg-slate-50 dark:hover:bg-slate-800/50">
                  <td className="p-2.5 font-bold">{intf.name}</td>
                  <td className="p-2.5">{intf.bandwidthMbps.toLocaleString()} Mbps</td>
                  <td className="p-2.5">
                    <span className={`px-2 py-0.5 rounded text-[10px] font-bold ${intf.area === 0 ? 'bg-amber-100 text-amber-900 dark:bg-amber-900/60 dark:text-amber-200' : 'bg-blue-100 text-blue-900 dark:bg-blue-900/60 dark:text-blue-200'}`}>
                      Area {intf.area} {intf.area === 0 ? '(Backbone)' : ''}
                    </span>
                  </td>
                  <td className="p-2.5">{intf.ipNetwork}</td>
                  <td className="p-2.5 text-right font-bold text-teal-600 dark:text-teal-400 text-sm">
                    {intf.calculatedCost}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* LSA Reference & Config Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* LSA Types Reference */}
        <div className="lg:col-span-6 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl p-5 shadow-sm space-y-3">
          <h2 className="text-sm font-bold uppercase tracking-wider text-slate-900 dark:text-white flex items-center space-x-2">
            <Layers className="h-4 w-4 text-teal-500" />
            <span>OSPF Link-State Advertisement (LSA) Types 1-7</span>
          </h2>

          <div className="space-y-2 max-h-[350px] overflow-y-auto pr-1">
            {lsaTypes.map((lsa, idx) => (
              <div key={idx} className="p-3 rounded-lg bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 space-y-1">
                <div className="flex justify-between items-center">
                  <span className="text-xs font-bold text-slate-900 dark:text-white font-mono">{lsa.type}</span>
                  <span className="text-[10px] px-2 py-0.5 rounded bg-teal-100 dark:bg-teal-900/60 text-teal-800 dark:text-teal-300 font-semibold font-mono">
                    {lsa.flood}
                  </span>
                </div>
                <p className="text-[11px] text-slate-500 dark:text-slate-400">{lsa.desc}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Cisco OSPF Config */}
        <div className="lg:col-span-6 bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-xl p-5 shadow-sm space-y-3 flex flex-col">
          <div className="flex justify-between items-center">
            <h2 className="text-sm font-bold uppercase tracking-wider text-slate-900 dark:text-white flex items-center space-x-2">
              <Terminal className="h-4 w-4 text-teal-500" />
              <span>Cisco IOS OSPF Config</span>
            </h2>
            <button
              onClick={() => copyToClipboard(ciscoOspfConfig, 'ospf')}
              className="text-xs px-2.5 py-1 rounded bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300 flex items-center space-x-1 font-mono"
            >
              {copiedKey === 'ospf' ? <Check className="h-3.5 w-3.5 text-emerald-500" /> : <Copy className="h-3.5 w-3.5" />}
              <span>Copy</span>
            </button>
          </div>
          <pre className="flex-1 p-3.5 bg-slate-950 text-teal-300 font-mono text-xs rounded-lg border border-slate-800 select-all overflow-x-auto min-h-[220px]">
            {ciscoOspfConfig}
          </pre>
        </div>
      </div>
    </div>
  );
};
